language: ruby
rvm:
  - 1.9.3
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc:
    channels:
      - "irc.freenode.net#selenium"
    on_success: change
    on_failure: change
    template:
      - "%{author} | %{commit} | %{message} | %{build_url}"
before_script:
  - for file in **/*.rb; do ruby -c $file || return 1; done